---
name: competition

users:
  - username: pitboss
    password: superlongpasssecurepassword1!

teams:
  # amount of teams to create
  amount: 2
  nameFormat: Team {{ .Team }}
  # Default password of all competition teams
  password: changeme123!

scoring:
  interval: 30 # seconds

engine:
  socket: /tmp/compscore.sock
  timeout: 5 # seconds

checks:
  - name: Roulette WinRM
    release:
      org: compscore
      repo: winrm
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.74
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Roulette LDAP (AD)
    release:
      org: compscore
      repo: ldap
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.74
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Blackjack GitLab
    release:
      org: compscore
      repo: web
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.71
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Blackjack IRC
    release:
      org: compscore
      repo: web
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.71
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Poker Mail
    release:
      org: compscore
      repo: web
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.70
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Poker SMB
    release:
      org: compscore
      repo: smb
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.70
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Baccarat DNS
    release:
      org: compscore
      repo: dns
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.73
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Baccarat SSH  
    release:
      org: compscore
      repo: ssh
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.73
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Slots Wordpress  
    release:
      org: compscore
      repo: web
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.72
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
  - name: Slots MySQL  
    release:
      org: compscore
      repo: mysql
      tag: latest
    credentials:
      username:
      password:
    target: 10.21.{{ .Team }}.72
    command:
    expectedOutput:
    weight:
    options:
      status_code:
      match:
      substring_match:
      regex_match:
